// <auto-generated />
using System;
using Lpl.Compliance.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lpl.Compliance.Api.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    partial class ComplianceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lpl.Compliance.Api.Models.ComplianceCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvisorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("RiskScore");

                    b.HasIndex("Status");

                    b.ToTable("ComplianceCases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdvisorName = "Ravi Kumar",
                            ClientName = "John Smith",
                            CreatedDate = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RiskScore = 82,
                            Status = "New"
                        },
                        new
                        {
                            Id = 2,
                            AdvisorName = "Priya Sharma",
                            ClientName = "Mary Johnson",
                            CreatedDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RiskScore = 45,
                            Status = "In Review"
                        },
                        new
                        {
                            Id = 3,
                            AdvisorName = "Anil Reddy",
                            ClientName = "Robert Brown",
                            CreatedDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RiskScore = 91,
                            Status = "Pending Documents"
                        },
                        new
                        {
                            Id = 4,
                            AdvisorName = "Sneha Rao",
                            ClientName = "Linda Davis",
                            CreatedDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RiskScore = 30,
                            Status = "Approved"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
